final int GEENVELD = -1;
final int LEEG = 0;
final int PION = 1;
final int ZWARTEPION = 2;
final int BONUSPION = 3;
final int PECHPION = 4;
final int GEKLIKTE_PION = 5;
final int GEKLIKTE_ZWARTE_PION = 6;
final int GRIJS = 100;
final int ZWART = 0;
final int WIT = 255;
final int ROOD = #FF0000;
final int ROODORANJE = #FF5900;
final int ORANJE = #FF5F1F;
final int GROEN = #00FF00;
final int ACHTERGROND = #1d8a99;
final int LICHT_GROEN = #81A490;
final int GEEL = #E7BB41;
final int FELGEEL = #E7BB41;
final int KNOP_INGEDRUKT_KLEUR = #A15E49;
final int FEL_LICHTGROEN = #1FB01C; 


//11 x 11 veld
int[][] veld1 = {
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, LEEG, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}
};
//17 x 17 veld
int[][]veld2 = {
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, LEEG, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}
};

//23 x 23 veld
int[][] veld3 = {
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, LEEG, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD} 
};

//29 x 29 veld
int[][] veld4 = {
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, LEEG, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, PION, PION, PION, PION, PION, PION, PION, PION, PION, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}, 
  {GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD, GEENVELD}
};


void tekenGrid(int speelVeld[][]) {
  background(GRIJS);
  for (int i = 0; i < speelVeld.length; i++) {
    for (int j = 0; j < speelVeld[i].length; j++) {
      int xVierkant = (width - GROOTTE * veld.length)/2 + j * GROOTTE;
      int yVierkant = (height - GROOTTE * veld.length)/2 + i * GROOTTE;
      int xCirkel = xVierkant + GROOTTE/2;
      int yCirkel = yVierkant + GROOTTE/2;
      switch (speelVeld[i][j]) {
      case LEEG:
        noStroke();
        fill(ACHTERGROND);
        rect(xVierkant, yVierkant, GROOTTE, GROOTTE);
        break;
      case PION:
        strokeWeight(2);
        stroke (ACHTERGROND);
        fill(ZWART);
        rect(xVierkant, yVierkant, GROOTTE, GROOTTE);
        fill(WIT);
        strokeWeight(0);
        circle(xCirkel, yCirkel, GROOTTE/8 * 5);
        break;
      case GEKLIKTE_PION:
        strokeWeight(2);
        stroke (ACHTERGROND);
        fill(ROOD);
        rect(xVierkant, yVierkant, GROOTTE, GROOTTE);
        fill(WIT);
        strokeWeight(0);
        circle(xCirkel, yCirkel, GROOTTE/8 * 5);
        break;
      case ZWARTEPION:
        strokeWeight(2);
        stroke (ACHTERGROND);
        fill(WIT);
        rect(xVierkant, yVierkant, GROOTTE, GROOTTE);
        fill(ZWART);
        strokeWeight(0);
        circle(xCirkel, yCirkel, GROOTTE/8 * 5);
        break;
      case GEKLIKTE_ZWARTE_PION:
        strokeWeight(2);
        stroke (ACHTERGROND);
        fill(ROOD);
        rect(xVierkant, yVierkant, GROOTTE, GROOTTE);
        fill(ZWART);
        strokeWeight(0);
        circle(xCirkel, yCirkel, GROOTTE/8 * 5);
        break;
      case BONUSPION:
        strokeWeight(2);
        stroke (ACHTERGROND);
        fill(ZWART);
        rect(xVierkant, yVierkant, GROOTTE, GROOTTE);
        fill(GROEN);
        strokeWeight(0);
        circle(xCirkel, yCirkel, GROOTTE/8 * 5);
        break;  
      case PECHPION:
        strokeWeight(2);
        stroke (ACHTERGROND);
        fill(ZWART);
        rect(xVierkant, yVierkant, GROOTTE, GROOTTE);
        fill(GROEN);
        strokeWeight(0);
        circle(xCirkel, yCirkel, GROOTTE/8 * 5);
        break;
      }
    }
  }
}
